export const INCIDENT_LIST_FETCHING = 'INCIDENT_LIST_FETCHING';
export const INCIDENT_LIST_FETCH_SUCCESS = 'INCIDENT_LIST_FETCH_SUCCESS';
export const INCIDENT_LIST_FETCH_ERROR = 'INCIDENT_LIST_FETCH_ERROR';
